[package]
name = "torrent-info"
version = "0.1.0"
authors = ["Nikola Kocic <nikolakocic@gmail.com>"]

[dependencies]
serde_bencode = "0.2.0"
serde_derive = "1.0.9"
serde = "1.0.9"
serde_bytes = "0.10.1"
serde_json = "1.0.2"
sha1 = "0.2.0"
bip_bencode = "0.3.0"
